CREATE TABLE IF NOT EXISTS game(GAME_ID SERIAL, GAME_STATUS VARCHAR(20) NOT NULL, PRIMARY KEY (GAME_ID) );
CREATE TABLE IF NOT EXISTS action(ACTION_ID SERIAL, GAME_ID INT NOT NULL, ACTION_NAME VARCHAR(20) NOT NULL, PRIMARY KEY (ACTION_ID), FOREIGN KEY (GAME_ID) REFERENCES game(GAME_ID));
CREATE TABLE IF NOT EXISTS figure(ID SERIAL, GAME_ID INT NOT NULL, FIGURE_ID INT NOT NULL, PRIMARY KEY (ID), FOREIGN KEY (GAME_ID) REFERENCES game(GAME_ID));
CREATE TABLE IF NOT EXISTS figure_type(FIGURE_ID SERIAL, FIGURE_POINTS VARCHAR(20) NOT NULL, PRIMARY KEY (FIGURE_ID) );