CREATE TABLE IF NOT EXISTS game
(
    GAME_ID     SERIAL,
    GAME_STATUS VARCHAR(20) NOT NULL,
    PRIMARY KEY (GAME_ID)
);
CREATE TABLE IF NOT EXISTS move
(
    MOVE_ID   SERIAL,
    GAME_ID   INT         NOT NULL,
    MOVE_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY (MOVE_ID),
    FOREIGN KEY (GAME_ID) REFERENCES game (GAME_ID)
);
CREATE TABLE IF NOT EXISTS figure
(
    GAME_ID   INT NOT NULL,
    FIGURE_ID INT NOT NULL,
    FOREIGN KEY (GAME_ID) REFERENCES game (GAME_ID),
    FOREIGN KEY (FIGURE_ID) REFERENCES figure_type (FIGURE_ID)
);
CREATE TABLE IF NOT EXISTS figure_type
(
    FIGURE_ID     SERIAL,
    FIGURE_POINTS VARCHAR(100) NOT NULL,
    PRIMARY KEY (FIGURE_ID)
);